Implement CropPhotoScreen with image cropping and saving functionality
swent-epfl-groupe07/eduverse-android pull request #173
Opened 2024-11-14 04:31 UTC by mehdixboutaleb

Feat: Implement CropPhotoScreen with Image Cropping, Saving, and Test Coverage

Added CropPhotoScreen composable to allow users to crop images by adjusting corner handles.
Implemented logic to update the crop area dynamically with drag gestures.
Introduced save functionality to crop and save images with proper scaling and offsets.
Integrated photo saving using PhotoViewModel and Firebase storage path.
Added test for verifying image loading and save button interaction in CropPhotoScreen with a coverage supposed to be above 80%.

Related to #117

<img width="354" alt="Capture d’écran 2024-11-14 à 05 26 45" src="https://github.com/user-attachments/assets/5400ba5d-f766-4af7-83fb-8a6b64c11e76">

2024-11-14 19:13 UTC, Fayroth requested changes
PR Review: Implement CropPhotoScreen with Image Cropping

Critical Issues:
1. App crashes on save:
- Incorrect scaling/offset calculations with hardcoded values
- Missing error handling for bitmap operations
- No memory management for bitmaps

2. Code Quality:
- No boundary validation for crop area
- Hardcoded UI values instead of dynamic calculations
- Inconsistent error handling patterns

3. Test Coverage:
- Mix of mockk and mockito frameworks
- Missing cleanup in tests
- Insufficient gesture testing
- No error case coverage

Required Changes:

CropPhotoScreen.kt:
- Implement proper bitmap memory management with remember()
- Add try-catch blocks for file operations
- Calculate offsets dynamically based on screen size
- Add crop area validation
- Handle screen rotation correctly

CropPhotoScreenTest.kt:
- Standardize on single mocking framework
- Add tearDown() for resource cleanup
- Expand gesture testing
- Add error scenario coverage
- Test rotation handling

The current implementation is unstable and needs these fixes before merging.

Related: #117

2024-11-14 19:13 UTC, Fayroth commented on app/src/main/java/com/github/se/eduverse/ui/camera/CropPhotoScreen.kt
Critical issues in CropPhotoScreen:

1. App crashes on save due to incorrect scaling/offset calculations. The hardcoded xOffset (134f) doesn't account for different screen sizes and rotations.

2. Memory management: Bitmap loading and processing needs proper recycling to prevent OOM errors. Should use remember() for bitmap state.

3. Error handling: Missing try-catch blocks for file operations and bitmap processing.

4. Validation: No boundary checks on crop rectangle dimensions before saving.

Suggested fixes:
- Calculate offset dynamically based on screen dimensions
- Add proper error handling and state management
- Implement bitmap recycling
- Validate crop dimensions before saving

Please fix these issues before merging as the current implementation is unstable.

2024-11-14 19:13 UTC, Fayroth commented on app/src/main/java/com/github/se/eduverse/MainActivity.kt
LGTM

2024-11-14 19:13 UTC, Fayroth commented on app/src/main/java/com/github/se/eduverse/ui/camera/PicTakenScreen.kt
LGTM

2024-11-14 19:13 UTC, Fayroth commented on app/src/androidTest/java/com/github/se/eduverse/ui/camera/CropPhotoScreenTest.kt
Test coverage issues in CropPhotoScreenTest:

1. Mock setup is incomplete - using both mockk and mockito which is inconsistent
2. Bitmap/File cleanup missing in tearDown()
3. test_cropPhotoScreen_dragCropArea is insufficient - only tests existence after drag, not actual position changes
4. Missing tests for:
  - Crop area boundary validation
  - Error cases (file operations, bitmap processing)
  - Screen rotation handling
  - Scale factor calculations

Add comprehensive tests for drag gesture behaviors and error scenarios before merging.

2024-11-27 12:22 UTC, abj10 approved these changes
# PR Review: CropPhotoScreen

## Overview
This PR introduces the `CropPhotoScreen` feature for cropping photos, accompanied by navigation enhancements and test cases to validate the functionality. Below is a detailed review of the changes:

### Strengths:
1. **Feature Implementation**:
   - `CropPhotoScreen` provides interactive cropping with draggable corners, enhancing user experience.
   - Utilizes `Bitmap` for image manipulation, integrating Firebase for storage (`Photo` model).

2. **Navigation Improvements**:
   - Proper routing from `PicTakenScreen` to `CropPhotoScreen` with `photoPath` encoding ensures seamless navigation.

3. **Test Coverage**:
   - Includes robust test cases for interactions such as dragging corners, save/cancel buttons, and image loading.

4. **Design Choices**:
   - Well-structured UI with corner handles, ensuring precise cropping interaction.
   - Dynamic dimensions for cropping ensure adaptability to different screen sizes.

---

### Areas for Improvement:
1. **Error Handling**:
   - File operations lack `try-catch` blocks, which could lead to crashes during unexpected failures.
   - Crop rectangle validation is minimal; edge cases (e.g., zero-width/height) should be better handled.

2. **Memory Management**:
   - Bitmap resources are not explicitly recycled, risking OutOfMemory (OOM) errors during prolonged usage.

3. **Dynamic Calculation Issues**:
   - Hardcoded values (e.g., drag thresholds) could lead to inconsistent behavior on different screen resolutions.

4. **Test Gaps**:
   - No validation of memory usage or boundary cases in cropping logic.
   - Tests assume consistent dimensions, not accounting for edge cases like invalid or oversized images.

---

### Suggestions:
- **Error Handling**:
  - Wrap file operations in `try-catch` blocks with fallback mechanisms or user feedback.
  - Validate crop dimensions before processing to prevent errors.

- **Memory Optimization**:
  - Explicitly recycle bitmaps after use (`bitmap.recycle()`).
  - Utilize `remember` for managing bitmap state to avoid unnecessary reloading.

- **Testing**:
  - Add tests for invalid crop areas (e.g., minimal dimensions, out-of-bounds errors).
  - Test memory-intensive operations with larger images to ensure stability.

- **Dynamic Adaptations**:
  - Replace hardcoded values (e.g., offsets, thresholds) with calculated metrics based on device screen dimensions.

---

### Summary:
This PR delivers a solid implementation of the photo cropping feature, but improvements in error handling, memory management, and test coverage will significantly enhance robustness and user experience.

2024-11-28 17:37 UTC, Fayroth approved these changes

2024-11-28 21:45 UTC, merged