Improve visual consistence of the app
swent-epfl-groupe07/eduverse-android pull request #197
Opened 2024-11-16 18:02 UTC by MathieuxC

This PR change the app so to improve visual consistence, especialy regarding colors and TopAppBar. The colors to use are in Color.kt and can be accessed using `MaterialTheme.colorScheme.<color you want>`

2024-11-17 12:02 UTC, AKallala requested changes
Great job going through all these files and doing the modifications. I just made some remarks and suggestions regarding the colors. Also I don't understand why do you didn't use the same top bar for all screens and why did you add the bottom bar to some secondary screens but not to others: for example you added the bottom bar to the pdf converter screen and the todo list but not to the pomodoro or the calculator screens

2024-11-17 14:17 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/ui/folder/DisplayFolder.kt
> +            backgroundColor = MaterialTheme.colorScheme.tertiaryContainer) {
Yes I noticed but didn't have the time to solve it yestedray, it is done now

2024-11-17 14:19 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/ui/folder/DisplayFolder.kt
>              modifier = Modifier.testTag("topAppBar"),
Yes I didn't use the same as for the rest of the app cause I thought it looked weird in white, but using this color for the whole app is a good idea

2024-11-17 15:00 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/ui/converter/PdfConverter.kt
> +      colors =
Yes, I don't know why the elevation turned this way, it is good now

2024-11-17 15:15 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/ui/search/UserProfileScreen.kt
> +                    selectedContentColor = MaterialTheme.colorScheme.primary)
Done

2024-11-17 22:21 UTC, AKallala requested changes
Well done, it looks much better this way. Thank you for your work. There's only a small thing left to change, it's the color of the circular progression of the pomodoro timer I think it's better if we set it to some blue color, that way it's in better harmony with the rest of the app's theme

2024-11-18 12:34 UTC, AKallala approved these changes
It's all good now, well done !

2024-11-18 12:34 UTC, merged