Implement the FolderViewModel
swent-epfl-groupe07/eduverse-android pull request #2
Opened 2024-10-09 15:07 UTC by MathieuxC

This Pull Request create some of the structure of the project, including :

- Creating the `model` and `ui` directory as in the bootcamp.
- Creating a `folder` directory in `model`, in which my code will be (see below).
- Creating a `FolderRepository` interface. An instance of it will be used to communicate between the view model and the firebase repository later on.
- Creating the folder screen, which doesn't display anything yet.

It also contains all created file for the view model of the folders (in `model/folder`), which are :

- The class `TimeTable`. It represent a one-week calendar of 7 days, each composed of 14 hours (from 07:00 to 21:00). Every hour of it can either be selected or not, which will correspond to hours in which it is planned to study the course of the folder. The class is composed of a private 2d mutable list (one dimension represent the day, the other one the hours). It has 2 set methods : one to select elements and the other one to unselect them.
 It also contains an access method to check if a time slot is selcted.
 The file also contains a private function to check if parameters (day and hours) are valid.
```
fun selectSlot(day: Int, hour: Int)
fun unselectSlot(day: Int, hour: Int)
fun isSelected(day: Int, hour: Int): Boolean
```

- The class `MyFile`. It represent a file with just a name. It also has attributes giving information about the creation time, last access time and total number of accesses. Those are useful to sort and display the files in a customable order. This class is likely to be updated when we will affine what kind of files we want and know how to save them (all on firebase, just the name on firebase while the file is localy, ...).
```
class MyFile(
    val name: String,
    val creationTime: Calendar,
    var lastAccess: Calendar,
    var numberAccess: Int
)
```

- The class `Folder`, which represent a folder and contains a list of `MyFile` (in a state flow, so that they will be updated on the ui), a name, an ID and a `TimeTable`.
```
class Folder(
    val files: MutableStateFlow<MutableList<MyFile>>,
    val name: String,
    val id: String,
    val timeTable: TimeTable
) 
```
- An enum class `FilterTypes`, to indicates the different ways the files can be sorted. It is situated in the same file as `Folder` and `MyFile`, as it is part of the folder logic. For now, there are 7 ways to sort the files : alphabeticly, by creation time (ascending and descending), by last access time (ascending and descending) and by number of accesses (ascending and descending).
- The `FolderViewModel` class itself. It will have a Factory for instanciation once we have a `FolderRepository`. It contains a list of all existing folders and a possibly `null` active folder (the one that is display, if one is). It also has methods to add, remove and update folder from the list of existing folders, get new ID to create folders, and one to sort the active folder.
```
val existingFolders: MutableList<Folder>
var activeFolder: Folder?
fun sortBy(filter: FilterTypes)
fun addFolder(folder: Folder)
fun deleteFolder(folder: Folder)
fun updateFolder(folder: Folder)
fun getNewUid(): String
```
Finaly, the PR also contains unit tests for the `TimeTable` and `FolderViewModel` classes.

Note: some commits are missing from the commit history,. This is due to the fact that we started working in a new repository after I coded most of the code of this PR. Those commits can be found in the project repository if needed, in the branch 'folder'.

2024-10-10 11:13 UTC, MathieuxC commented
I have changed the list of files of the folders so that it is not a MutableStateFlow.

2024-10-11 19:20 UTC, ismailIBNMAJAH approved these changes

2024-10-12 09:51 UTC, merged

2024-10-12 16:59 UTC, AKallala requested changes
There are things to change but it's a good start.

2024-10-12 16:59 UTC, AKallala commented on app/src/main/java/com/github/se/eduverse/model/folder/FolderViewModel.kt
> +  fun deleteFolder(folder: Folder) {
Same as for add folder the logic of the variables updates should be defined inside the on success lambda

2024-10-12 16:59 UTC, AKallala commented on app/src/main/java/com/github/se/eduverse/model/folder/FolderViewModel.kt
> +  fun updateFolder(folder: Folder) {
Same as for the other functions

2024-10-12 16:59 UTC, AKallala commented on app/src/main/java/com/github/se/eduverse/model/folder/FolderViewModel.kt
I think that you should add a function getUserFolders that updates the value of _existingFolders, also I think it's a good idea to add functions as addFileToFolder, renameFolder, etc that all call updateFolder, also a function selectFolder that updates the activeFolder should be added like it's done in the bootcamp

2024-10-12 16:59 UTC, AKallala commented on app/src/main/java/com/github/se/eduverse/model/folder/MyFile.kt
I think that MyFile should have a property userId to set the user that owns the file, and be able to add controls in other parts of the implementation to avoid revealing files of a user to other users. Also I think we should add a fileId property used to store the file on the db.

2024-10-12 16:59 UTC, AKallala commented on app/src/main/java/com/github/se/eduverse/model/folder/TimeTable.kt
I think that this should be a TimeTableViewModel class to manage the overall time table, and then I think we should store the time tables of the users in the db, but we can discuss this with the rest of the team