(feat) AI Assistant
swent-epfl-groupe07/eduverse-android pull request #257
Opened 2024-12-06 01:47 UTC by abj10

# **(feat) AI Chat Assistant**

### **Screenshots**

<img width="331" alt="Capture d’écran 2024-12-06 à 02 42 53" src="https://github.com/user-attachments/assets/24e82fc4-2481-4059-b586-e49c5e1e18dc">
<img width="334" alt="Capture d’écran 2024-12-06 à 02 45 11" src="https://github.com/user-attachments/assets/a85a1eb3-e9b0-4ed8-90d4-6e7a518200c8">

---

### **What?**

This PR introduces initial integration of an AI Chat Assistant. It includes repositories, navigation updates, and UI components to support the new feature.

---

### **Key Changes**

#### 1. **AI Assistant Repository**
- **`AiAssistantRepository.kt`:** Handles AI-related data management and interactions.

#### 2. **AI Assistant Screen**
- **`AiAssistantScreen.kt `:** Handles the UI of the AI Assistant.

#### 3. **UI Enhancements**
- **`DashboardScreen.kt`:** Updated to accommodate AI assistant functionalities.
- **`NavigationActions.kt`:** Added routes for AI Assistant-related screens.

#### 4. **Backend Preparations**
- Modified `MainActivity.kt` to initialize AI-related dependencies.
- Updated `Widget.kt` with assistant-specific attributes.

#### 5. **Testing Framework**
- **`assistant/AiAssistantScreenTest`:** Added tests for the UI.

---

### **Why?**
These updates enable:
- Seamless integration of AI-powered features in the Eduverse ecosystem.
- Enhanced user experience through intelligent assistant capabilities.

---

### **How?**
- Implemented repository patterns for managing AI Assistant data.
- Updated navigation and UI to reflect the addition of AI functionalities.
- Created a test structure to ensure feature reliability.

---

### **Type of Change**
- [x] New Feature (AI Assistant integration)
- [x] Enhancement (navigation and UI updates)

---

### **Checklist**
- [x] Code adheres to project standards.
- [x] Verified navigation flows and repository functionality.
- [x] Integrated UI components with backend services.
- [x] Added UI and Unit tests.

---

### **Files Changed**

#### **New Files**
- `app/src/main/java/com/github/se/eduverse/repository/AiAssistantRepository.kt`
- `app/src/main/java/com/github/se/eduverse/ui/assistant/AiAssistantScreen.kt`
- `app/src/test/java/com/github/se/eduverse/repository/AssistantTest.kt`
- `app/src/androidTest/java/com/github/se/eduverse/ui/assistant/`

#### **Core Files**
- `app/src/main/java/com/github/se/eduverse/MainActivity.kt`
- `app/src/main/java/com/github/se/eduverse/model/Widget.kt`
- `app/src/main/java/com/github/se/eduverse/ui/dashboard/DashboardScreen.kt`
- `app/src/main/java/com/github/se/eduverse/ui/navigation/NavigationActions.kt`

2024-12-10 17:00 UTC, AKallala requested changes
Well done on implementing this new feature, it adds substantial value to the app. However I pointed out some changes that need to be done. 
First, the changes made to DashboardScreen need to be rolled back, as they overwrite modifications introduced in #247. This is also the reason the CI is currently failing. Additionally, I suggest creating a view model for this feature to better adhere to MVVM principles and improve the separation of concerns. I’ve also provided several other suggestions to enhance code quality.

2024-12-11 21:03 UTC, abj10 commented on app/src/main/java/com/github/se/eduverse/ui/dashboard/DashboardScreen.kt
Yes indeed, there was a problem while resolving conflicts, I did a revert to last commit before merge to solve the problem

2024-12-12 11:10 UTC, abj10 commented
> You're still discarding changes merged to main branch.

I didn't discard anything, it's an issue generated by the reverts. Indeed previous merge main into this branch caused problems

2024-12-13 06:08 UTC, AKallala commented
This PR has been recreated in a new PR #283 because of the merge issues

2024-12-13 06:08 UTC, closed without merging