Feat/loading
swent-epfl-groupe07/eduverse-android pull request #45
Opened 2024-10-14 00:33 UTC by abj10

## What?

This PR integrates the `LoadingScreen` into the navigation flow and updates `MainActivity`, `NavigationActions`, and `SignIn` components.

## Why?

To provide smoother transitions between the login screen, loading screen, and dashboard

## How?

- Updated `MainActivity` to include the new `LoadingScreen` in the navigation flow.
- Modified `SignInScreen` to route through `LoadingScreen` after authentication.
- Adjusted `NavigationActions` to support navigation to the `LoadingScreen`.
- Added `LoadingScreen` to facilitate transitions between login and dashboard.
- Introduced `PermissionDeniedScreen` to handle camera permission requests.
- Updated branding with new logos (`eduverse_logo.png`, `eduverse_logo_alone.png`).

## Type of change

- [x] New feature (integrated `LoadingScreen` and updated navigation flow).
- [x] UX improvements (smoother transitions between screens and new logos).

## Checklist

- [x] Code follows the project's style guidelines.
- [x] Verified that navigation transitions work as expected.
- [x] Tested the Loading Screen.
- [x] Updated branding with new logos.

2024-10-14 18:01 UTC, MathieuxC requested changes
The changes look good to me, but you should write test.

2024-10-17 20:22 UTC, Fayroth approved these changes
You could also add a loading circle for ui purposes but otherwise its all good, looks good to me.

2024-10-17 20:22 UTC, Fayroth commented on app/src/main/java/com/github/se/eduverse/ui/authentification/Loading.kt
I dont think you should use the auth.currentID to bypass the connection step. It always lead to the AUTH screen everytime.

2024-10-17 21:25 UTC, Fayroth approved these changes
LGTM

2024-10-18 02:31 UTC, MathieuxC approved these changes

2024-10-18 03:59 UTC, merged