feat: Implement image save functionality in Firebase Storage with MVV…
swent-epfl-groupe07/eduverse-android pull request #58
Opened 2024-10-16 19:58 UTC by ismailIBNMAJAH

…M pattern

- Integrated Firebase Storage save functionality into the PicTakenScreen using the MVVM architecture.
- Updated PicTakenScreen to include logic for saving images and navigating back on success.
- Added unit and UI tests for the PicTakenScreen to validate save functionality and UI elements. -Added tests for the PhotoRepository and PhotoViewModel
- Removed French comments as requested in the previous PR for improved code readability and consistency.

2024-10-16 21:30 UTC, MathieuxC requested changes
It looks good, great job ! I pointed out a couple details you could change, but this is great

2024-10-16 21:30 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/MainActivity.kt
> +
Initiate those in the EduverseApp, instead of doing it in MainActivity and the passing the view model to EduverseApp

2024-10-16 21:30 UTC, MathieuxC commented on app/src/main/java/com/github/se/eduverse/ui/camera/PicTakenScreen.kt
> +  val ownerId = "user123"
I feel like you should include a FirebaseAuth to the arguments of the function and use auth.currentUser.uid here

2024-10-18 02:08 UTC, ismailIBNMAJAH commented
bad PR, it s content was transmitted into PR #64

2024-10-18 02:08 UTC, closed without merging